name: Mirror ButBucket

on:
  pull_request:
    types: [ closed ]

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # <-- clone with complete history
    - name: Push
      uses: heussd/mirror-to-bitbucket-github-action@v2
      with:
        username: MarkLBoomi
        spacename: boomii
        repository: PSO-Groovy-Toolkit
        password: ${{ secrets.BITBUCKET_PASSWORD }}
